#!/usr/bin/env python3

import os
import subprocess
import sys

GHC_WARNINGS = [
    '-Wall',
    '-fwarn-incomplete-record-updates',
    '-fwarn-incomplete-uni-patterns',
]

GHC = os.environ.get('STACK_YAML', 'ghc-8.2')

if GHC >= 'ghc-8':
    GHC_WARNINGS += ['-Wcompat', '-Wredundant-constraints']

GHC_OPTIONS = GHC_WARNINGS + ['-Werror']

stack = os.environ.get('STACK', 'stack')

subprocess.check_call(
    stack.split()
    + ['test', '--haddock', '--no-haddock-deps']
    + ['--ghc-options=' + option for option in GHC_OPTIONS]
    + sys.argv[1:]
)
