#!/usr/bin/env python3

import os
import subprocess

GHC_WARNINGS = [
    '-Wall',
    '-fwarn-incomplete-record-updates',
    '-fwarn-incomplete-uni-patterns',
]

if os.environ.get('ETA', ''):
    os.chdir('crdt/')
    GHC_OPTIONS = GHC_WARNINGS + ['-Werror']
    def etlas(*args):
        subprocess.check_call(
            ['etlas', '--enable-send-metrics']
            + list(args)
        )
    etlas('update')
    etlas('select', 'latest')
    etlas('install', '--dependencies-only')
    etlas('build', *['--ghc-options=' + option for option in GHC_OPTIONS])
else:
    GHC = os.environ.get('STACK_YAML', 'ghc-8.2')
    if GHC >= 'ghc-8':
        GHC_WARNINGS += ['-Wcompat', '-Wredundant-constraints']
    GHC_OPTIONS = GHC_WARNINGS + ['-Werror']
    stack = os.environ.get('STACK', 'stack')
    subprocess.check_call(
        stack.split()
        + ['test', '--haddock', '--no-haddock-deps']
        + ['--ghc-options=' + option for option in GHC_OPTIONS]
    )
