os: linux

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - export STACK="stack --no-terminal --install-ghc"

install:
  # Download and unpack the stack executable
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64
    | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

jobs:
  include:
    - {name: build and test everything, script: test/script}
    - {name: haddock, script: $STACK haddock}
    - {name: hlint, script: $STACK build hlint --exec 'hlint .'}
