name: crdt
version: '2.0' # ComVer
category: Distributed Systems
copyright: 2017 Yuriy Syrovetskiy, Nikolay Loginov
maintainer: Yuriy Syrovetskiy <cblp@cblp.su>
license: BSD3
license-file: LICENSE
synopsis: Conflict-free replicated data types
description:
  Definitions of CmRDT and CvRDT. Implementations for some classic CRDTs.
github: cblp/crdt

dependencies:
  - base >= 4.9 && < 4.11
  - containers

library:
  dependencies:
    - mtl
  source-dirs: lib

tests:
  test:
    dependencies:
      - tasty
      - tasty-quickcheck

      - crdt

    main: Main.hs
    source-dirs: test
