name: crdt
version: '0.2' # ComVer
category: Distributed Systems
maintainer: Yuriy Syrovetskiy <cblp@cblp.su>
license: BSD3
license-file: LICENSE
synopsis: Conflict-free replicated data types
description:
  Definitions of CmRDT and CvRDT. Implementations for some classic CRDTs.
github: cblp/crdt

dependencies:
  - base >= 4.9 && < 4.10
  - vector

library:
  source-dirs: lib

tests:
  test:
    dependencies:
      - QuickCheck
      - tasty
      - tasty-quickcheck

      - crdt

    main: Main.hs
    source-dirs: test
