name: crdt
version: '0.1' # ComVer

dependencies:
  - base
  - vector

library:
  source-dirs: lib

tests:
  test:
    dependencies:
      - QuickCheck
      - tasty
      - tasty-quickcheck

      - crdt

      - primitive

    main: Main.hs
    source-dirs: test
