name: crdt
version: '6.2' # ComVer
category: Distributed Systems
copyright:
  2017 Yuriy Syrovetskiy, Nikolay Loginov;
  2018 Yuriy Syrovetskiy
maintainer: Yuriy Syrovetskiy <cblp@cblp.su>
license: BSD3
license-file: LICENSE
synopsis: Conflict-free replicated data types
description:
  Definitions of CmRDT and CvRDT. Implementations for some classic CRDTs.
github: cblp/crdt

dependencies:
  - base >= 4.9 && < 4.11
  - containers

library:
  dependencies:
    - binary
    - bytestring
    - mtl
    - network-info
    - safe
    - stm
    - time
  source-dirs: lib

tests:
  test:
    dependencies:
      - mtl
      - QuickCheck
      - QuickCheck-GenT
      - quickcheck-instances
      - tasty
      - tasty-discover >= 4.1  # fixed discovery bug
      - tasty-quickcheck

      - crdt

    main: Main.hs
    source-dirs: test
