name: crdt
version: '0.4' # ComVer
category: Distributed Systems
author:
  Yuriy Syrovetskiy <cblp@cblp.su>,
  Nikolay Loginov <kemphack@mail.ru>
copyright:
  © 2017  Yuriy Syrovetskiy <cblp@cblp.su>, Nikolay Loginov <kemphack@mail.ru>
maintainer: Yuriy Syrovetskiy <cblp@cblp.su>
license: BSD3
license-file: LICENSE
synopsis: Conflict-free replicated data types
description:
  Definitions of CmRDT and CvRDT. Implementations for some classic CRDTs.
github: cblp/crdt

dependencies:
  - base >= 4.9 && < 4.10
  - containers

library:
  source-dirs: lib

tests:
  test:
    dependencies:
      - QuickCheck
      - tasty
      - tasty-quickcheck

      - crdt

    main: Main.hs
    source-dirs: test
