resolver: lts-10.1

extra-deps:
  - tasty-discover-4.1.1

  # for liquidhaskell:
  - aeson-0.11.3.0
  - dotgen-0.4.2
  - fgl-visualize-0.1.0.1
  - intern-0.9.1.4
  - liquid-fixpoint-0.7.0.5
  - liquidhaskell-0.8.0.3
  - located-base-0.1.1.1
