name: crdt
version: '9.0' # ComVer
category: Distributed Systems
copyright:
  2017 Yuriy Syrovetskiy, Nikolay Loginov;
  2018 Yuriy Syrovetskiy
maintainer: Yuriy Syrovetskiy <cblp@cblp.su>
license: BSD3
license-file: LICENSE
synopsis: Conflict-free replicated data types
description:
  Definitions of CmRDT and CvRDT. Implementations for some classic CRDTs.
github: cblp/crdt

dependencies:
  - base >= 4.9 && < 4.11
  - containers
  - vector

library:
  dependencies:
    - binary
    - bytestring
    - Diff
    - hashable
    - mtl
    - network-info
    - safe
    - stm
    - time
  source-dirs: lib
